version: '3.8'
services:
  app       build:
    context: .
    dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'